[package]
name = "windns-sd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
serde = "1.0.166"
windows-service = "0.6.0"
astro-dnssd= "0.3.2"